#!/bin/sh -e

mkdir -p /var/run/postgresql/9.5-main.pg_stat_tmp
chown postgres:postgres /var/run/postgresql/9.5-main.pg_stat_tmp
exec /sbin/setuser postgres /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf

