---
# file: slave.yml
- hosts: all
  gather_facts: no
  user: ubuntu
  sudo: yes
  tasks:
  - name: Configure user 'ubuntu'
    authorized_key: user=ubuntu key="{{item}}"
    with_file:
    - ~/.ssh/id_rsa.pub
    - templates/Jenkins_aws_system.pem.pub

  - name: Configure user 'jenkins'
    file: path=/opt/jenkins state=directory
  - user: name=jenkins home=/opt/jenkins state=present shell=/bin/bash
  - file: path=~jenkins/ state=directory owner=jenkins group=jenkins
  - file: path=~jenkins/.ssh state=directory owner=jenkins group=jenkins mode=700
  - authorized_key: user=jenkins key="{{ item }}"
    with_file:
    - ~/.ssh/id_rsa.pub
    - templates/jenkins_id_rsa.pub
    - templates/Jenkins_aws_system.pem.pub
  - copy: src=templates/91-cloudimg-jenkins dest=/etc/sudoers.d/91-cloudimg-jenkins
          mode=440
  - copy: src=~/.ssh/jenkins_id_rsa dest=~jenkins/.ssh/id_rsa
          owner=jenkins group=jenkins mode=600 backup=no
  - copy: src=templates/jenkins_id_rsa.pub dest=~jenkins/.ssh/id_rsa.pub
          owner=jenkins group=jenkins mode=600 backup=no
  - copy: src=templates/jenkins_ssh_config dest=~jenkins/.ssh/config
          owner=jenkins group=jenkins mode=600 backup=no
  - file: path=~jenkins/.m2 state=directory owner=jenkins group=jenkins
  - copy: src=/opt/build/hudson/m2remote/settings.xml dest=~jenkins/.m2/settings.xml
          owner=jenkins group=jenkins

  - name: Packages upgrade/install
    apt: upgrade=yes update_cache=yes
  - apt: state=latest pkg=$item
    with_items:
    - openjdk-6-jdk
    - openjdk-7-jdk
    - git
    - mercurial
    - subversion
    - firefox
    - chromium-browser
    - ant
    - ant-contrib
    - imagemagick
    - ffmpeg
    - ffmpeg2theora
    - lynx
    - sysstat
    - logtail
    - gawk
    - vim
    - wget
    - curl
    - unzip
    - moreutils
    # Funkload requirements
    - python-dev
    - python-setuptools
    - python-webunit
    - python-docutils
    - gnuplot
    - python-reportlab
    - python-pypdf
  - apt: state=latest pkg=tcpwatch-httpproxy install_recommends=no
  - shell: easy_install -f http://funkload.nuxeo.org/snapshots/ -U funkload
  - shell: update-alternatives --set editor /usr/bin/vim.basic
  - file: src=/usr/lib/jvm/java-1.7.0-openjdk-amd64 path=/usr/lib/jvm/java-7-openjdk state=link

  - name: Tooling
    file: path=/opt/build state=directory owner=root group=root
  # TODO: find another solution than local rsync
#  - file: path=/opt/build/keystores state=directory owner=jenkins group=jenkins
#  - local_action: command rsync -a /opt/build/keystores
#                  jenkins@${inventory_host}:/opt/build/keystores
  - file: path=/opt/build/hudson state=directory owner=jenkins group=jenkins
  - copy: src=/opt/build/hudson/gradle.properties dest=/opt/build/hudson/gradle.properties
          owner=jenkins group=jenkins
  - file: path=/opt/build/tools state=directory owner=jenkins group=jenkins
  - copy: src=templates/use_mnt.sh dest=~jenkins/use_mnt.sh
          mode=755 owner=jenkins group=jenkins

  - name: Maven 2.x
    uri: creates=/opt/build/tools/maven2
         url=http://www.us.apache.org/dist/maven/maven-2/2.2.1/binaries/apache-maven-2.2.1-bin.tar.gz
         dest=/tmp/apache-maven-2.2.1-bin.tar.gz
  - command: creates=/opt/build/tools/maven2 chdir=/opt/build/tools
             tar zxvf /tmp/apache-maven-2.2.1-bin.tar.gz
  - file: src=/opt/build/tools/apache-maven-2.2.1 path=/opt/build/tools/maven2 state=link
  - shell: update-alternatives --install /usr/bin/mvn mvn /opt/build/tools/maven2/bin/mvn 1
  - file: path=/tmp/apache-maven-2.2.1-bin.tar.gz state=absent

  - name: Maven 3.x
    uri: creates=/opt/build/tools/maven3
         url=http://www.us.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
         dest=/tmp/apache-maven-3.0.5-bin.tar.gz
  - command: creates=/opt/build/tools/maven3 chdir=/opt/build/tools
             tar zxvf /tmp/apache-maven-3.0.5-bin.tar.gz
  - file: src=/opt/build/tools/apache-maven-3.0.5 path=/opt/build/tools/maven3 state=link
  - shell: update-alternatives --install /usr/bin/mvn mvn /opt/build/tools/maven3/bin/mvn 2
  - file: path=/tmp/apache-maven-3.0.5-bin.tar.gz state=absent

  - name: Gradle 1.x
    uri: creates=/opt/build/tools/gradle
         url=http://services.gradle.org/distributions/gradle-1.6-bin.zip
         dest=/tmp/gradle-1.6-bin.zip
  - command: creates=/opt/build/tools/gradle
             unzip /tmp/gradle-1.6-bin.zip -d /opt/build/tools/
  - file: src=/opt/build/tools/gradle-1.6 path=/opt/build/tools/gradle state=link
  - shell: update-alternatives --install /usr/bin/gradle gradle /opt/build/tools/gradle/bin/gradle 1
  - file: path=/tmp/gradle-1.6-bin.zip state=absent

  - name: Spot instance Jenkins callback script
    get_url: url=https://github.com/jenkinsci/ec2-plugin/raw/master/src/main/webapp/AMI-Scripts/ubuntu-init.py 
             dest=/usr/bin/userdata mode=0750
  - shell: '! grep userdata /etc/rc.local && sed -i "s,^exit 0,python /usr/bin/userdata\\n&," /etc/rc.local'
  - shell: "! grep 176.57.246.10 /etc/hosts && echo '\n176.57.246.10 thorin thorin.in.nuxeo.com qa qa.nuxeo.org qapriv qapriv.nuxeo.org\n' >> /etc/hosts"
