---
- name: Get AWS ID
  debug: msg="{{lookup('env','AWS_ACCESS_KEY_ID')}}"
  no_log: true
  register: aws_id
- name: Get AWS secret
  debug: msg="{{lookup('env','AWS_SECRET_ACCESS_KEY')}}"
  no_log: true
  register: aws_secret
- name: Stop if credentials are missing
  fail: msg="You must have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in your environment"
  when: aws_id.msg == "" or aws_secret.msg == ""

- name: Set Firefox 24 as default
  alternatives: name=firefox link=/usr/bin/firefox path=/opt/build/tools/firefox-24/firefox
- s3: bucket={{s3_bucket}} region={{s3_region}}
      object=/{{s3_config_path}}/settings.xml dest=//opt/jenkins/.m2/settings.xml mode=get
      aws_access_key={{aws_id.msg}} aws_secret_key={{aws_secret.msg}} overwrite=different
  become_user: jenkins
- file: path=/opt/jenkins/.m2/settings.xml state=file owner=jenkins group=jenkins

- name: Get jenkins base home from S3
  command: aws s3 sync s3://{{s3_bucket}}/{{s3_config_path}}/jenkins_home/ /opt/jenkins --region={{s3_region}}
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_id.msg}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret.msg}}"
  register: homesyncpriv
  changed_when: homesyncpriv.stdout != ""
- file: path=/opt/jenkins/.docker state=directory owner=jenkins group=jenkins mode=0700
- file: path=/opt/jenkins/.docker/config.json state=file owner=jenkins group=jenkins mode=0600
