---
- name: Dep (Go)
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/dep-linux-amd64 mode=geturl
  changed_when: false
  failed_when: false
  register: godep
- get_url: url=https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64
           dest=cache/dep-linux-amd64
  when: godep.url is not defined

