---
- name: Java 6
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/jdk-6u45-linux-x64.bin mode=geturl
  changed_when: false
  failed_when: false
  register: java6
- command: "wget -q -Ocache/jdk-6u45-linux-x64.bin --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/6u45-b06/jdk-6u45-linux-x64.bin'"
  args:
    creates: cache/jdk-6u45-linux-x64.bin
  when: java6.url is not defined

- name: Java 7
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/jdk-7u80-linux-x64.tar.gz mode=geturl
  changed_when: false
  failed_when: false
  register: java7
- command: "wget -q -Ocache/jdk-7u80-linux-x64.tar.gz --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz'"
  args:
    creates: cache/jdk-7u80-linux-x64.tar.gz
  when: java7.url is not defined

- name: Java 8
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/jdk-8u191-linux-x64.tar.gz mode=geturl
  changed_when: false
  failed_when: false
  register: java8
- command: "wget -q -Ocache/jdk-8u191-linux-x64.tar.gz --no-check-certificate --header 'Cookie: oraclelicense=accept-securebackup-cookie' 'http://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/jdk-8u191-linux-x64.tar.gz'"
  args:
    creates: cache/jdk-8u191-linux-x64.tar.gz
  when: java8.url is not defined

- name: OpenJDK 9
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/openjdk-9.0.1_linux-x64_bin.tar.gz mode=geturl
  changed_when: false
  failed_when: false
  register: openjdk9
- command: "wget -q -Ocache/openjdk-9.0.1_linux-x64_bin.tar.gz --no-check-certificate 'http://download.java.net/java/GA/jdk9/9.0.1/binaries/openjdk-9.0.1_linux-x64_bin.tar.gz'"
  args:
    creates: cache/openjdk-9.0.1_linux-x64_bin.tar.gz
  when: openjdk9.url is not defined

- name: OpenJDK 11
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/openjdk-11.0.2_linux-x64_bin.tar.gz mode=geturl
  changed_when: false
  failed_when: false
  register: openjdk11
- command: "wget -q -Ocache/openjdk-11.0.2_linux-x64_bin.tar.gz --no-check-certificate 'https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz'"
  args:
    creates: cache/openjdk-11.0.2_linux-x64_bin.tar.gz
  when: openjdk11.url is not defined

