---
- name: NodeJS 4
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v4.5.0-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs4
- get_url: url=https://nodejs.org/dist/v4.5.0/node-v4.5.0-linux-x64.tar.xz
           dest=cache/node-v4.5.0-linux-x64.tar.xz
  when: nodejs4.url is not defined

- name: NodeJS 6.4
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v6.4.0-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs64
- get_url: url=https://nodejs.org/dist/v6.4.0/node-v6.4.0-linux-x64.tar.xz
           dest=cache/node-v6.4.0-linux-x64.tar.xz
  when: nodejs64.url is not defined

- name: NodeJS 6.9.2 LTS
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v6.9.2-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs69
- get_url: url=https://nodejs.org/dist/v6.9.2/node-v6.9.2-linux-x64.tar.xz
           dest=cache/node-v6.9.2-linux-x64.tar.xz
  when: nodejs69.url is not defined

- name: NodeJS 8.11.3 LTS
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v8.11.3-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs811
- get_url: url=https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz
           dest=cache/node-v8.11.3-linux-x64.tar.xz
  when: nodejs811.url is not defined

- name: NodeJS 10.13.0 LTS
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v10.13.0-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs1013
- get_url: url=https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.xz
           dest=cache/node-v10.13.0-linux-x64.tar.xz
  when: nodejs1013.url is not defined

- name: NodeJS 12.13.0 LTS
  s3: bucket={{s3_bucket}} region={{s3_region}} object=/{{s3_tools_path}}/node-v12.13.0-linux-x64.tar.xz mode=geturl
  changed_when: false
  failed_when: false
  register: nodejs1213
- get_url: url=https://nodejs.org/dist/v12.13.0/node-v12.13.0-linux-x64.tar.xz
           dest=cache/node-v12.13.0-linux-x64.tar.xz
  when: nodejs1213.url is not defined
