---
- name: Install Docker's dependencies
  apt:
    name: "apt-transport-https ca-certificates curl gnupg-agent software-properties-common"

- name: Add Docker's public GPG key to the APT keyring
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    update_cache: true

- name: Install Docker
  apt:
    name: "docker-ce"
    state: present
