---
- name: Add docker apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=9DC858229FC7DD38854AE2D88D81803C0EBFCD88
- name: Add docker repo
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list
- name: Update apt cache
  apt: update_cache=yes
- name: Install docker
  apt: name=docker-ce state=present

