---
- name: Add golang ppa
  apt_repository: repo='ppa:gophers/archive'
- name: Update apt cache
  apt: update_cache=yes
- name: Install golang 1.9
  apt: name='golang-1.9-go' state=latest
- name: Symlink go
  file: path=/usr/bin/go src=/usr/lib/go-1.9/bin/go state=link
- name: Symlink gofmt
  file: path=/usr/bin/gofmt src=/usr/lib/go-1.9/bin/gofmt state=link

- name: Check for dep
  stat: path=/usr/bin/dep
  register: godep_installed
- name: Get dep
  s3: bucket={{s3_bucket}} region={{s3_region}}
      object=/{{s3_tools_path}}/dep-linux-amd64 dest=/usr/bin/dep mode=get
      aws_access_key={{aws_id.msg}} aws_secret_key={{aws_secret.msg}}
  when: not godep_installed.stat.exists
- file: path=/usr/bin/dep mode=0755 owner=root group=root

