---
- name: Get the Google Linux package signing key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
- stat: path=/etc/apt/sources.list.d/google-chrome.list
  register: google_apt_rc
- name: Add Google Chrome stable repo
  copy: content="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list
  when: google_apt_rc.stat.exists == false
- name: Update apt cache
  apt: update_cache=yes
  when: google_apt_rc.stat.exists == false
- name: Install Google Chrome
  apt: pkg=google-chrome-stable state=latest
  when: google_apt_rc.stat.exists == false
- name: Install ChromeDriver dependencies
  apt: pkg={{item}} state=latest
  with_items:
    - libnss3
    - libgconf-2-4
- name: Install ChromeDriver 2.36
  get_url: url=http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
           dest=/tmp/chromedriver_linux64.zip
- command: creates=/usr/bin/chromedriver chdir=/usr/bin
           unzip /tmp/chromedriver_linux64.zip
- file: path=/usr/bin/chromedriver mode=0755
