---
- name: Get the MongoDB public key
  apt_key: url=https://www.mongodb.org/static/pgp/server-4.0.asc state=present validate_certs=False
- name: Set up the location of the stable repository
  copy: src=mongodb-org-4.0.list dest=/etc/apt/sources.list.d/mongodb-org-4.0.list
- name: Update apt cache
  apt: update_cache=yes
- name: Create systemctl mock symlink
  file: src=/bin/true path=/usr/local/bin/systemctl state=link
- name: Install MongoDB client
  apt: name={{item}} state=present
  with_items:
  - mongodb-org
- name: Remove systemctl mock symlink
  file: path=/usr/local/bin/systemctl state=absent
- name: Create MongoDB runit dir
  file: path=/etc/service/mongodb state=directory
- name: Add MongoDB startup script
  copy: src=mongodb dest=/etc/service/mongodb/run mode=0755
