---
- name: Add redis repo
  apt_repository: repo='ppa:chris-lea/redis-server' state=present
- name: Upgrade/install Redis packages
  apt: state=latest name={{item}}
  with_items:
  - redis-server
  - redis-tools
  tags: redis
- name: Do not listen on IPv6
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: '::1'
    state: absent
- name: Listen on IPv4 loopback
  lineinfile:
    dest: /etc/redis/redis.conf
    line: 'bind 127.0.0.1'

